---
name: SurvivalGame
version: 0.1.0
main: LuizMinecrapt\skywars\Main
author: VsrStudio
api: 5.0.0
description: Survival Game VsrStudio

commands:
  skywars:
    permission: 'skywars.permission'

permissions:
  skywars.permission:
    default: true
...
