---
name: SurvivalGame
version: 1.0.0
main: VsrStudio\sg\Main
author: VsrStudio
api: 5.0.0
description: Survival Game VsrStudio

commands:
  survivalgame:
    permission: 'survivalgame.permission'

permissions:
  survivalgame.permission:
    default: true
...
